/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function BlogDetailPage() {
  return (
    <div className="items-start bg-white flex flex-col">
      <div className="items-center self-stretch bg-white flex w-full flex-col justify-center px-16 py-9 max-md:max-w-full max-md:px-5">
        <div className="flex ml-0 items-center justify-between gap-5 max-md:max-w-full max-md:flex-wrap">
          <div className="items-stretch flex gap-3 my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/367a985da78628a27eaa46fb883f9f45a25f261d1c09d7fb913b5778ff6797ef?"
              className="aspect-square object-contain object-center w-11 overflow-hidden shrink-0 max-w-full"
            />
            <div className="text-pink-500 text-xl font-bold leading-8 self-center grow whitespace-nowrap my-auto">
              eazyPregnancy
            </div>
          </div>
          <div className="justify-between items-center self-stretch flex gap-5 pl-20 max-md:max-w-full max-md:flex-wrap max-md:pl-5">
            <div className="items-stretch border border-[color:var(--gray-text-100,#DCD8DC)] bg-white flex gap-1 my-auto px-6 py-2 rounded-lg border-solid max-md:px-5">
              <div className="text-zinc-300 text-sm leading-6 grow whitespace-nowrap">
                Search blogs, events, programs etc
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/ae58fe9cd012cfc18da91a1a8ccb7d71d18388073e311870cbac09c898aa3b8a?"
                className="aspect-square object-contain object-center w-4 overflow-hidden self-center shrink-0 max-w-full my-auto"
              />
            </div>
            <div className="justify-between items-start self-stretch flex gap-5 pr-2 py-1 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
              <div className="items-stretch self-center flex gap-1 my-auto p-1 rounded-lg">
                <div className="text-zinc-800 text-sm font-semibold leading-6 grow whitespace-nowrap">
                  Research
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b1c3358a323ab00ae95184806960427d1c339fade91f8c72537e05c3c9a3bef6?"
                  className="aspect-square object-contain object-center w-4 overflow-hidden self-center shrink-0 max-w-full my-auto"
                />
              </div>
              <div className="items-stretch self-center flex gap-1 my-auto p-1 rounded-lg">
                <div className="text-zinc-800 text-sm font-semibold leading-6 grow whitespace-nowrap">
                  Community
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b1c3358a323ab00ae95184806960427d1c339fade91f8c72537e05c3c9a3bef6?"
                  className="aspect-square object-contain object-center w-4 overflow-hidden self-center shrink-0 max-w-full my-auto"
                />
              </div>
              <div className="text-zinc-800 text-sm font-semibold leading-6 self-center my-auto">
                About Us
              </div>
              <div className="text-white text-sm font-semibold leading-6 whitespace-nowrap items-stretch bg-pink-500 self-stretch grow justify-center px-6 py-2 rounded-lg max-md:px-5">
                Login
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/666a3d66f7b3f84794561537b09c2095d6ce0fa5758e2b0a61e45acbe115181a?"
                className="aspect-square object-contain object-center w-6 overflow-hidden self-center shrink-0 max-w-full my-auto"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="items-center border border-[color:var(--gray-text-100,#DCD8DC)] bg-white flex gap-1 ml-80 mt-20 px-8 py-3 rounded-lg border-solid self-start max-md:ml-2.5 max-md:mt-10 max-md:px-5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/074cab1c2c1b08b2135512d20717325a4df312c90ac7a3c418ac065daa1d934c?"
          className="aspect-square object-contain object-center w-5 overflow-hidden shrink-0 max-w-full my-auto"
        />
        <div className="text-zinc-800 text-base font-semibold leading-6 self-stretch grow whitespace-nowrap">
          Back to Blogs
        </div>
      </div>
      <div className="text-white text-sm font-bold leading-6 whitespace-nowrap items-stretch bg-pink-500 justify-center ml-80 mt-16 px-4 py-1 rounded-[40px] self-start max-md:ml-2.5 max-md:mt-10">
        FEATURED
      </div>
      <div className="self-center text-zinc-800 text-5xl font-bold leading-[72px] w-[768px] max-w-full mt-3 max-md:text-4xl max-md:leading-[67px] max-sm:px-4">
        Why Yoga is necessary in pregnancy?
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        A little description about this blog, not more than 250 words. Nunc non
        mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu rhoncus neque.
        Nullam tempor tempor magna a ultricies. Sed leo eros, volutpat gravida
        ante at.
      </div>
      <div className="self-center bg-zinc-300 flex w-[768px] shrink-0 max-w-full h-0.5 flex-col mt-6" />
      <div className="items-stretch self-center flex w-[768px] max-w-full gap-3 mt-6 px-5 max-md:flex-wrap">
        <div className="text-zinc-600 text-xl leading-8 grow shrink basis-auto max-md:max-w-full">
          by Dr. Mamta Kulkarni
        </div>
        <div className="items-stretch flex justify-between gap-5">
          <div className="text-zinc-400 text-xl leading-8 grow whitespace-nowrap">
            5 min read
          </div>
          <div className="items-center flex justify-between gap-1.5">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2309dcd0c4a8aa4463795b8fad5a02f3f3e586edc2ce964260fb04fb8b4645a5?"
              className="aspect-square object-contain object-center w-[19px] overflow-hidden shrink-0 max-w-full my-auto"
            />
            <div className="text-teal-900 text-xl font-bold leading-8 self-stretch grow whitespace-nowrap">
              4.8
            </div>
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[1.8] object-contain object-center w-full self-stretch overflow-hidden mt-20 max-md:max-w-full max-md:mt-10"
      />
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        Section heading
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[1.45] object-contain object-center w-[768px] self-center overflow-hidden max-w-full mt-20 max-md:mt-10"
      />
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        Section heading
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[1.45] object-contain object-center w-[768px] self-center overflow-hidden max-w-full mt-20 max-md:mt-10"
      />
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        Section heading
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        Section heading
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[1.45] object-contain object-center w-[768px] overflow-hidden self-center max-w-full mt-20 max-md:mt-10"
      />
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        Section heading
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-neutral-900 text-3xl font-semibold leading-10 w-[768px] max-w-full mt-20 max-md:mt-10 max-sm:px-4">
        That’s all
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-8 max-sm:text-base max-sm:leading-6 max-sm:px-4">
        Nunc non mi vulputate, vehicula nisi vel, gravida dolor. Mauris eu
        rhoncus neque. Nullam tempor tempor magna a ultricies. Sed leo eros,
        volutpat gravida ante at, vestibulum porttitor ante. In consectetur,
        purus a ultricies tempus, nisi dui commodo turpi.
      </div>
      <div className="self-center text-zinc-600 text-xl leading-8 w-[768px] max-w-full mt-6 max-sm:px-4">
        Thank you for reading. Hope it helped.
      </div>
      <div className="max-w-full justify-center self-center border border-[color:var(--gray-text-100,#DCD8DC)] backdrop-blur-[2px] bg-white flex w-[768px] flex-col mt-40 p-6 rounded-xl border-solid items-start max-md:mt-10 max-md:px-5 max-sm:w-auto max-sm:self-center max-sm:mx-4 max-sm:px-4">
        <img
          loading="lazy"
          srcSet="..."
          className="aspect-square object-contain object-center w-10 overflow-hidden max-w-full"
        />
        <div className="self-stretch text-zinc-800 text-xl font-bold leading-8 mt-3 max-md:max-w-full">
          Mamta Kulkarni
        </div>
        <div className="self-stretch text-zinc-600 text-base leading-6 mt-1 max-md:max-w-full">
          Pregnancy Specialist
        </div>
        <div className="self-stretch text-zinc-600 text-base leading-6 mt-3 max-md:max-w-full">
          Lorem iopsum dolor sit amet consectuter adipiscing elit.
        </div>
        <div className="items-stretch flex gap-3 mt-3 max-md:justify-center">
          <div className="text-zinc-800 text-sm font-semibold leading-6 whitespace-nowrap items-stretch bg-zinc-100 aspect-[2.03125] justify-center px-4 py-1 rounded-[40px]">
            Tag 1
          </div>
          <div className="text-zinc-800 text-sm font-semibold leading-6 whitespace-nowrap items-stretch bg-zinc-100 aspect-[2.03125] justify-center px-4 py-1 rounded-[40px]">
            Tag 2
          </div>
          <div className="text-zinc-800 text-sm font-semibold leading-6 whitespace-nowrap items-stretch bg-zinc-100 grow justify-center px-4 py-1 rounded-[40px]">
            +12 more
          </div>
        </div>
      </div>
      <div className="items-center self-stretch bg-zinc-100 flex w-full flex-col justify-center mt-20 px-16 py-12 max-md:max-w-full max-md:mt-10 max-md:px-5">
        <div className="flex w-full max-w-[1200px] flex-col items-stretch mt-16 mb-12 max-md:max-w-full max-md:my-10">
          <div className="text-zinc-800 text-6xl font-semibold leading-[90px] max-md:max-w-full max-md:text-4xl max-md:leading-[67px]">
            Explore more blogs
          </div>
          <div className="mt-16 max-md:max-w-full max-md:mt-10">
            <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
                <div className="items-stretch flex grow flex-col max-md:mt-10">
                  <div className="flex-col overflow-hidden relative flex aspect-[1.5726872246696035] w-full pl-16 pr-2.5 pt-2.5 pb-12 items-end max-md:pl-5">
                    <img
                      loading="lazy"
                      srcSet="..."
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />
                    <div className="relative items-center bg-zinc-800 flex w-[59px] max-w-full gap-1 mb-24 px-2 py-0.5 rounded-3xl max-md:mb-10">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/5bb6ae8758c704301b9bcd9fadb195fca3ce8f86857221d359c70ad800d05f9a?"
                        className="aspect-square object-contain object-center w-full overflow-hidden shrink-0 flex-1 my-auto"
                      />
                      <div className="text-white text-sm font-bold leading-6 self-stretch grow whitespace-nowrap">
                        4.8
                      </div>
                    </div>
                  </div>
                  <div className="text-zinc-800 text-xl font-bold leading-8 mt-6">
                    Blog title goes here
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-2">
                    Lorem iopsum dolor sit amet consectuter adipiscing elit.
                  </div>
                  <div className="bg-zinc-100 flex shrink-0 h-px flex-col mt-2" />
                  <div className="items-stretch flex justify-between gap-3 mt-2">
                    <div className="text-zinc-600 text-sm leading-6 grow shrink basis-auto">
                      by Dr. Mamta Kulkarni
                    </div>
                    <div className="text-zinc-400 text-sm leading-6 whitespace-nowrap">
                      5 min read
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                <div className="items-stretch flex grow flex-col max-md:mt-10">
                  <div className="flex-col overflow-hidden relative flex aspect-[1.577092511013216] w-full pl-16 pr-3 pt-2.5 pb-12 items-end max-md:pl-5">
                    <img
                      loading="lazy"
                      srcSet="..."
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />
                    <div className="relative items-center bg-zinc-800 flex w-[59px] max-w-full gap-1 mb-24 px-2 py-0.5 rounded-3xl max-md:mb-10">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b96620cfe7c42184eb3793a8cb6e828955ebf40b47f8607db7bd335f01f28b93?"
                        className="aspect-square object-contain object-center w-full overflow-hidden shrink-0 flex-1 my-auto"
                      />
                      <div className="text-white text-sm font-bold leading-6 self-stretch grow whitespace-nowrap">
                        4.8
                      </div>
                    </div>
                  </div>
                  <div className="text-zinc-800 text-xl font-bold leading-8 mt-6">
                    Blog title goes here
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-2">
                    Lorem iopsum dolor sit amet consectuter adipiscing elit.
                  </div>
                  <div className="bg-zinc-100 flex shrink-0 h-px flex-col mt-2" />
                  <div className="items-stretch flex justify-between gap-3 mt-2">
                    <div className="text-zinc-600 text-sm leading-6 grow shrink basis-auto">
                      by Dr. Mamta Kulkarni
                    </div>
                    <div className="text-zinc-400 text-sm leading-6 whitespace-nowrap">
                      5 min read
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                <div className="items-stretch flex grow flex-col max-md:mt-10">
                  <div className="flex-col overflow-hidden relative flex aspect-[1.5726872246696035] w-full pl-16 pr-2.5 pt-2.5 pb-12 items-end max-md:pl-5">
                    <img
                      loading="lazy"
                      srcSet="..."
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />
                    <div className="relative items-center bg-zinc-800 flex w-[59px] max-w-full gap-1 mb-24 px-2 py-0.5 rounded-3xl max-md:mb-10">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e991f3daf78b888b3742b31bd3aab36d23b096e013916bb663a5e40273e11937?"
                        className="aspect-square object-contain object-center w-full overflow-hidden shrink-0 flex-1 my-auto"
                      />
                      <div className="text-white text-sm font-bold leading-6 self-stretch grow whitespace-nowrap">
                        4.8
                      </div>
                    </div>
                  </div>
                  <div className="text-zinc-800 text-xl font-bold leading-8 mt-6">
                    Blog title goes here
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-2">
                    Lorem iopsum dolor sit amet consectuter adipiscing elit.
                  </div>
                  <div className="bg-zinc-100 flex shrink-0 h-px flex-col mt-2" />
                  <div className="items-stretch flex justify-between gap-3 mt-2">
                    <div className="text-zinc-600 text-sm leading-6 grow shrink basis-auto">
                      by Dr. Mamta Kulkarni
                    </div>
                    <div className="text-zinc-400 text-sm leading-6 whitespace-nowrap">
                      5 min read
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="items-center self-stretch bg-white flex w-full flex-col justify-center px-16 py-11 max-md:max-w-full max-md:px-5">
        <div className="flex w-full max-w-[1200px] flex-col mt-12 max-md:max-w-full max-md:mt-10">
          <div className="justify-between items-stretch self-stretch flex w-full gap-5 max-md:max-w-full max-md:flex-wrap">
            <div className="items-stretch flex justify-between gap-3">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3d4178822d3ae0a77359ce04072c2c541bc33b2c5539523a0e7ae13d29ac1bf3?"
                className="aspect-square object-contain object-center w-16 overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-neutral-900 text-2xl font-bold leading-9 self-center grow whitespace-nowrap my-auto">
                eazyPregnancy
              </div>
            </div>
            <div className="items-stretch self-center flex justify-between gap-5 my-auto px-6 max-md:justify-center max-md:px-5">
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-contain object-center w-8 overflow-hidden shrink-0 max-w-full"
              />
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-contain object-center w-8 overflow-hidden shrink-0 max-w-full"
              />
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-contain object-center w-8 overflow-hidden shrink-0 max-w-full"
              />
            </div>
          </div>
          <div className="self-stretch bg-zinc-300 flex shrink-0 h-px flex-col mt-10 max-md:max-w-full" />
          <div className="self-stretch mt-10 max-md:max-w-full">
            <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
                <div className="items-stretch self-stretch flex flex-col max-md:mt-6">
                  <div className="text-zinc-800 text-lg font-semibold leading-7">
                    Research
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-6">
                    Blogs
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Articles
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Events
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="items-stretch self-stretch flex grow flex-col max-md:mt-6">
                  <div className="text-zinc-800 text-lg font-semibold leading-7">
                    Community
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-6">
                    Doctors
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Community
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Yoga Centres
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Our Programs
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="items-stretch self-stretch flex grow flex-col max-md:mt-6">
                  <div className="text-zinc-800 text-lg font-semibold leading-7">
                    About us
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-6">
                    About us
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Help
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Terms and Conditions
                  </div>
                  <div className="text-zinc-600 text-base leading-6 mt-3">
                    Legal
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="items-stretch self-stretch flex flex-col max-md:mt-6">
                  <div className="text-zinc-800 text-lg font-semibold leading-7">
                    Contact us
                  </div>
                  <div className="items-stretch flex justify-between gap-2 mt-6">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/64dd0556fd52e75304143c334a0eba9274ba7b266c2c4412f32584116c6f0b08?"
                      className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-zinc-600 text-base leading-6 grow shrink basis-auto">
                      eazypregnancy@email.com
                    </div>
                  </div>
                  <div className="items-stretch flex justify-between gap-2 mt-3">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c75a7b4186fe1869087186b22b0c770594b2ec016ef66a0e4d8ec16caec2d6bd?"
                      className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-zinc-600 text-base leading-6 grow shrink basis-auto">
                      +91 99999 77777
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="self-stretch bg-zinc-300 flex shrink-0 h-px flex-col mt-10 max-md:max-w-full" />
          <div className="text-zinc-600 text-base leading-6 self-center whitespace-nowrap mt-4">
            Copyright text
          </div>
        </div>
      </div>
    </div>
  );
}
